-- ============================================================
-- Migration: Hybrid Search AI Auto-Pilot System
-- Sopaloka v2.3.0
-- Tanggal: 2026-09-17
-- Deskripsi: Full-Text Search, Kamus Sinonim, Telemetry AI
-- ============================================================

-- 1. Ekstensi
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS pg_cron;

-- 2. FTS: Tambah kolom search_vector ke listings
ALTER TABLE public.listings
ADD COLUMN IF NOT EXISTS search_vector tsvector
GENERATED ALWAYS AS (
  setweight(to_tsvector('indonesian', coalesce(title, '')), 'A') ||
  setweight(to_tsvector('indonesian', coalesce(category, '')), 'B') ||
  setweight(to_tsvector('indonesian', coalesce(description, '')), 'C')
) STORED;

CREATE INDEX IF NOT EXISTS listings_search_idx
ON public.listings USING GIN(search_vector);

-- 3. Tabel Perekam Jejak Pencarian (Bahan Bakar AI)
CREATE TABLE IF NOT EXISTS public.search_telemetry (
    id bigint generated by default as identity primary key,
    search_query text NOT NULL,
    clicked_listing_id text REFERENCES public.listings(id),
    created_at timestamptz DEFAULT now() NOT NULL
);

ALTER TABLE public.search_telemetry ENABLE ROW LEVEL SECURITY;

CREATE POLICY "allow_insert_search_telemetry"
ON public.search_telemetry FOR INSERT
WITH CHECK (true);

-- 4. Tabel Kamus Sinonim
CREATE TABLE IF NOT EXISTS public.search_synonyms (
  id bigint generated by default as identity primary key,
  term text NOT NULL,
  synonyms text[] NOT NULL DEFAULT '{}',
  source text NOT NULL DEFAULT 'manual' CHECK (source IN ('manual', 'ai_learned')),
  created_at timestamptz DEFAULT now() NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS search_synonyms_term_idx
ON public.search_synonyms(lower(term));

ALTER TABLE public.search_synonyms ENABLE ROW LEVEL SECURITY;

CREATE POLICY "allow_read_synonyms"
ON public.search_synonyms FOR SELECT
USING (true);

-- 5. Isi Kamus Master Sinonim E-Commerce Indonesia
INSERT INTO public.search_synonyms (term, synonyms, source) VALUES
  ('hp', ARRAY['handphone','ponsel','smartphone','telepon','hape','henpon'], 'manual'),
  ('handphone', ARRAY['hp','ponsel','smartphone','telepon','hape'], 'manual'),
  ('laptop', ARRAY['notebook','komputer','pc','netbook'], 'manual'),
  ('tv', ARRAY['televisi','television','tivi'], 'manual'),
  ('kulkas', ARRAY['lemari es','refrigerator','freezer'], 'manual'),
  ('ac', ARRAY['air conditioner','pendingin','aircond','aircon'], 'manual'),
  ('headset', ARRAY['headphone','earphone','earbuds','tws'], 'manual'),
  ('cas', ARRAY['charger','carger','pengisi daya','adaptor'], 'manual'),
  ('baterai', ARRAY['batere','batre','battery'], 'manual'),
  ('kamera', ARRAY['camera','cam','fotografi'], 'manual'),
  ('motor', ARRAY['sepeda motor','motorik','moped'], 'manual'),
  ('mobil', ARRAY['kendaraan','otomotif','car'], 'manual'),
  ('skok', ARRAY['shockbreaker','shock breaker','sokbreker','sok','suspensi'], 'manual'),
  ('shockbreaker', ARRAY['skok','sokbreker','sok','suspensi'], 'manual'),
  ('pelek', ARRAY['velg','velk','rim','roda'], 'manual'),
  ('ban', ARRAY['tyre','tire','karet ban'], 'manual'),
  ('karbu', ARRAY['karburator','carbu','carburator'], 'manual'),
  ('knalpot', ARRAY['knalpon','kenalpot','muffler','exhaust'], 'manual'),
  ('baju', ARRAY['pakaian','kaos','kemeja','atasan','busana','kain'], 'manual'),
  ('kaos', ARRAY['t-shirt','tshirt','baju','atasan'], 'manual'),
  ('celana', ARRAY['pants','jeans','bawahan','rok'], 'manual'),
  ('sepatu', ARRAY['shoes','sandal','alas kaki','sneakers'], 'manual'),
  ('jaket', ARRAY['jacket','outer','sweater','hoodie'], 'manual'),
  ('kursi', ARRAY['sofa','bangku','tempat duduk','chair'], 'manual'),
  ('meja', ARRAY['table','desk'], 'manual'),
  ('kasur', ARRAY['matras','bed','tempat tidur'], 'manual'),
  ('lemari', ARRAY['cabinet','almari','wardrobe'], 'manual'),
  ('kompor', ARRAY['stove','dapur','masak'], 'manual'),
  ('mesin cuci', ARRAY['washing machine','laundry'], 'manual'),
  ('sepeda', ARRAY['bike','bicycle','pit'], 'manual'),
  ('seli', ARRAY['sepeda lipat','folding bike','lipat'], 'manual'),
  ('MTB', ARRAY['mountain bike','sepeda gunung','downhill'], 'manual'),
  ('jual', ARRAY['dijual','lelang','sale'], 'manual'),
  ('beli', ARRAY['cari','dicari','wanted'], 'manual'),
  ('nego', ARRAY['negosiasi','tawar','bargain'], 'manual'),
  ('tt', ARRAY['tukar tambah','tukartambah','trade in'], 'manual'),
  ('cod', ARRAY['cash on delivery','ketemuan','bayar ditempat'], 'manual'),
  ('ori', ARRAY['original','asli','genuine'], 'manual'),
  ('kw', ARRAY['tiruan','replika','imitasi','palsu'], 'manual'),
  ('mulus', ARRAY['baru','bagus','terawat','kondisi baik'], 'manual'),
  ('bekas', ARRAY['second','seken','used','preloved'], 'manual'),
  ('spare part', ARRAY['sparepart','suku cadang','onderdil','part'], 'manual'),
  ('sparepart', ARRAY['spare part','suku cadang','onderdil','part'], 'manual')
ON CONFLICT (lower(term)) DO NOTHING;

-- 6. AI SQL Function: Belajar Sinonim dari Telemetry
CREATE OR REPLACE FUNCTION public.learn_synonyms_from_telemetry()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  rec RECORD;
  pair_count integer := 0;
BEGIN
  FOR rec IN
    WITH clicks_per_listing AS (
      SELECT
        lower(trim(search_query)) AS query,
        clicked_listing_id,
        COUNT(*) AS click_count
      FROM public.search_telemetry
      WHERE clicked_listing_id IS NOT NULL
        AND created_at > now() - interval '30 days'
        AND length(trim(search_query)) >= 3
      GROUP BY lower(trim(search_query)), clicked_listing_id
      HAVING COUNT(*) >= 3
    ),
    synonym_candidates AS (
      SELECT
        a.query AS term_a,
        b.query AS term_b,
        COUNT(DISTINCT a.clicked_listing_id) AS shared_listings
      FROM clicks_per_listing a
      JOIN clicks_per_listing b
        ON a.clicked_listing_id = b.clicked_listing_id
        AND a.query < b.query
      GROUP BY a.query, b.query
      HAVING COUNT(DISTINCT a.clicked_listing_id) >= 2
    )
    SELECT term_a, term_b FROM synonym_candidates
  LOOP
    INSERT INTO public.search_synonyms (term, synonyms, source)
    VALUES (rec.term_a, ARRAY[rec.term_b], 'ai_learned')
    ON CONFLICT (lower(term)) DO UPDATE
      SET synonyms = (
        SELECT ARRAY(SELECT DISTINCT unnest(search_synonyms.synonyms || ARRAY[rec.term_b]))
      ),
      updated_at = now(),
      source = CASE WHEN search_synonyms.source = 'manual' THEN 'manual' ELSE 'ai_learned' END;

    INSERT INTO public.search_synonyms (term, synonyms, source)
    VALUES (rec.term_b, ARRAY[rec.term_a], 'ai_learned')
    ON CONFLICT (lower(term)) DO UPDATE
      SET synonyms = (
        SELECT ARRAY(SELECT DISTINCT unnest(search_synonyms.synonyms || ARRAY[rec.term_a]))
      ),
      updated_at = now(),
      source = CASE WHEN search_synonyms.source = 'manual' THEN 'manual' ELSE 'ai_learned' END;

    pair_count := pair_count + 1;
  END LOOP;

  RAISE NOTICE '[learn_synonyms] Selesai. % pasang sinonim baru ditemukan.', pair_count;
END;
$$;

-- 7. RLS: districts (hanya baca)
ALTER TABLE public.districts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "allow_read_districts"
ON public.districts FOR SELECT USING (true);

-- 8. pg_cron: Jadwal AI setiap malam 02:00 WIB (19:00 UTC)
SELECT cron.schedule(
  'sopaloka-learn-synonyms',
  '0 19 * * *',
  $$SELECT public.learn_synonyms_from_telemetry()$$
);
